name: Format Python code
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install black==23.3 isort==5.12
      - name: Format with black and isort
        run: |
          black .
          isort .
          
      - name: Set up Javascript
        uses: actions/setup-node@v3
        with:
          node-version: 18          
      - name: Install Node.js dependencies
        run: |
          npm ci && npm test
      - name: Run lintersa of javascript
        uses: wearerequired/lint-action@v2
        with:
          eslint: true
          prettier: true
          
      - name: Check for changes
        id: changes
        run: |
          if [[ $(git status --porcelain) ]]; then
            echo "is_formatted=true" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Pull Request
        if: steps.changes.outputs.is_formatted == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.PULL_REQUEST_ACTION }}
          title: "Autoformat Python code by GitHub Action"
          commit-message: "style(🤖): 🎨format Python code with Black and isort"
          body: |
            There appear to be some Python formatting issues in this pull request. I have automatically formatted the code using Black and isort. Please review the changes and merge this pull request if they look good to you.

           
           
      

      
          
      
